### ISSUE TITLE
JSON 1.4 required - but not in marmalade repository.

### ISSUE THREAD

**Issue by Knusper** [vibhavp/emacs-xkcd#14]
I see you have added your package to the marmalade repository. But you require json 1.4 - which is not provided in that repository. Users of marmalade will thus not be able to install your package.

**Comment by vibhavp** [comment]
I just updated the package in the marmalade repository. Could you now try installing?

**Comment by Knusper** [comment]
yes - now the installation of the package xkcd worked now - but it appears that there are 2 packages in marmalade doing the same thing emacs-xkcd and xkcd. Both are by you - although the latter one seems to be fresher.

**Comment by vibhavp** [comment]
Strange. I removed emacs-xkcd from marmalade using their client (https://marmalade-repo.org/profile/vibhavp/ lists only xkcd). Maybe it takes time for the package to get completely erased from the archive.
