### ISSUE TITLE
Feature request: explain xkcd

### ISSUE THREAD

**Issue by zealotrush** [vibhavp/emacs-xkcd#28]
First of all, great package!  Thanks for your work!

Some of the XKCD comics are difficult to follow -- at least for me.  There is a website called [explain xkcd](https://www.explainxkcd.com/wiki/index.php/Main_Page) which is quite useful.  I suggest that it would be interesting if the package can fetch the content from _explain xkcd_ and display it along the way.

**Comment by dcorking** [comment]
`e` is bound to `(xkcd-open-explanation-browser)` which will open the relevant page in your browser

**Comment by zealotrush** [comment]
Cool!  Thank you!
